### Part 1

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("Mall_Customers.csv")

In [3]:
df

     CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
0             1    Male   19                  15                      39
1             2    Male   21                  15                      81
2             3  Female   20                  16                       6
3             4  Female   23                  16                      77
4             5  Female   31                  17                      40
..          ...     ...  ...                 ...                     ...
195         196  Female   35                 120                      79
196         197  Female   45                 126                      28
197         198    Male   32                 126                      74
198         199    Male   32                 137                      18
199         200    Male   30                 137                      83

[200 rows x 5 columns]

In [4]:
df.head()

   CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
0           1    Male   19                  15                      39
1           2    Male   21                  15                      81
2           3  Female   20                  16                       6
3           4  Female   23                  16                      77
4           5  Female   31                  17                      40

In [5]:
df.tail()

     CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
195         196  Female   35                 120                      79
196         197  Female   45                 126                      28
197         198    Male   32                 126                      74
198         199    Male   32                 137                      18
199         200    Male   30                 137                      83

In [6]:
df.dtypes

CustomerID                 int64
Gender                    object
Age                        int64
Annual Income (k$)         int64
Spending Score (1-100)     int64
dtype: object

In [7]:
df.columns

Index(['CustomerID', 'Gender', 'Age', 'Annual Income (k$)',
       'Spending Score (1-100)'],
      dtype='object')

In [8]:
df.isnull().sum()

CustomerID                0
Gender                    0
Age                       0
Annual Income (k$)        0
Spending Score (1-100)    0
dtype: int64

In [9]:
bins = [0, 20, 30, 45, 60, 100]

In [10]:
labels = ['Teenage', 'Yound', 'Middle_Age', 'Adult', 'Old']

In [11]:
df['Age_Range'] = pd.cut(df['Age'], bins = bins, labels = labels, right = False)

In [12]:
grouped = df.groupby('Age_Range')['Spending Score (1-100)']

C:\Users\adity\AppData\Local\Temp\ipykernel_9008\1885991117.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  grouped = df.groupby('Age_Range')['Spending Score (1-100)']

In [13]:
max_vals = grouped.max()

In [15]:
max_vals

Age_Range
Teenage       92
Yound         97
Middle_Age    99
Adult         60
Old           59
Name: Spending Score (1-100), dtype: int64

In [16]:
min_vals = grouped.min()

In [17]:
min_vals

Age_Range
Teenage       5
Yound         5
Middle_Age    1
Adult         4
Old           3
Name: Spending Score (1-100), dtype: int64

In [18]:
mean_vals = grouped.mean()

In [19]:
mean_vals

Age_Range
Teenage       46.500000
Yound         61.953488
Middle_Age    55.710526
Adult         35.183673
Old           43.000000
Name: Spending Score (1-100), dtype: float64

In [20]:
median_vals = grouped.median()
median_vals

Age_Range
Teenage       49.0
Yound         66.0
Middle_Age    60.5
Adult         42.0
Old           48.5
Name: Spending Score (1-100), dtype: float64

In [21]:
std_vals = grouped.std()
std_vals

Age_Range
Teenage       22.697617
Yound         23.200937
Middle_Age    29.273795
Adult         17.306879
Old           16.673332
Name: Spending Score (1-100), dtype: float64

In [22]:
count_vals = grouped.count()

In [23]:
count_vals

Age_Range
Teenage       12
Yound         43
Middle_Age    76
Adult         49
Old           20
Name: Spending Score (1-100), dtype: int64

In [24]:
stats_summary = grouped.describe()

In [25]:
stats_summary

            count       mean        std  min    25%   50%    75%   max
Age_Range
Teenage      12.0  46.500000  22.697617  5.0  40.50  49.0  56.00  92.0
Yound        43.0  61.953488  23.200937  5.0  49.50  66.0  80.00  97.0
Middle_Age   76.0  55.710526  29.273795  1.0  31.75  60.5  78.25  99.0
Adult        49.0  35.183673  17.306879  4.0  16.00  42.0  48.00  60.0
Old          20.0  43.000000  16.673332  3.0  42.50  48.5  52.75  59.0